name: Build
on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Dep
      run: sudo apt install fuse libfuse2
    - name: Construct AppDir
      run: make
    - name: Get appimagetool
      run: |
        curl --location -o appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool
    - name: Make AppImage
      run: ./appimagetool build/calibre.AppDir
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@master
      with:
        name: Calibre-x86_64.AppImage
        path: ./Calibre-x86_64.AppImage
